spring:
  application:
    name: io-project
  profiles:
    active: local
  ai:
    openai:
      enabled: false
      api-key: ${OPENAI_API_KEY}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9098/realms/io-project"

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/io-db
    username: user
    password: password
    pool:
      enabled: true
      initial-size: 5
      max-size: 20
      validation-query: SELECT 1

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

storage:
  local:
    base-path: classpath:storage/

server:
  port: 8080

logging:
  level:
    org.springframework.r2dbc: DEBUG
