name: Scala CI - Sentinel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test-sentinel:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'sbt'

      - name: Install sbt
        run: |
          echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | sudo tee /etc/apt/sources.list.d/sbt.list
          curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x99E82A75642AC823" | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install -y sbt

      - name: Show Docker info (for Testcontainers)
        run: docker info

      - name: Run ZIO + Testcontainers tests in Sentinel
        working-directory: sentinel
        run: sbt test

      - name: Upload dependency graph
        uses: scalacenter/sbt-dependency-submission@v1
        with:
          working-directory: sentinel
